version: "3.8"

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # Tells Docker to start Redis before starting the API
    depends_on:
      - redis

  # Our newly created background worker service
  worker:
    build: ./backend
    # Overrides the default Dockerfile command to run the worker script instead of the API
    command: python worker.py
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  redis:
    # Uses the official, lightweight Alpine Linux version of Redis
    image: redis:7-alpine
    ports:
      # Exposes the default Redis port so our apps can connect to it
      - "6379:6379"
