version: "3.8"

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # Tells Docker to start Redis before starting the API
    depends_on:
      - redis
      - mongodb
    # Tells Python to print logs to the console immediately
    environment:
      - PYTHONUNBUFFERED=1
    # Securely injects the Gemini API key into the API container as well
    env_file:
      - ./backend/.env

  # Our newly created background worker service
  worker:
    build: ./backend
    # Overrides the default Dockerfile command to run the worker script instead of the API
    command: python worker.py
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - mongodb
    # Tells Python to print logs to the console immediately
    environment:
      - PYTHONUNBUFFERED=1
    # This injects our secret API keys securely into the worker container
    env_file:
      - ./backend/.env

  redis:
    # Uses the official, lightweight Alpine Linux version of Redis
    image: redis:7-alpine
    ports:
      # Exposes the default Redis port so our apps can connect to it
      - "6379:6379"

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"              # Exposes the default MongoDB port to your local machine
    volumes:
      - mongo_data:/data/db        # Mounts a persistent volume so data survives a restart

# Defines the persistent hard drive space for MongoDB
volumes:
  mongo_data: